---
name: Version docker image

on:
  create:
    tags:
      - v*
jobs:
  build-and-push-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set tag variable
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set action link variable
        run: echo "LINK=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/badhouseplants/storekeeper-service:${{ env.TAG }}
          labels: |
            action_id=${{ github.action }}
            action_link=${{ env.LINK }}
            actor=${{ github.actor }}
            sha=${{ github.sha }}
            ref=${{ github.ref }}